### ISSUE TITLE
blank terminal

### ISSUE THREAD

**Issue by casperdcl** [platformio/platformio-atom-ide-terminal#805] opened 2019-11-09 21:33 UTC
- [x] I have reset Atom to defaults prior to submitting report.
### Description

Terminal does not initialise - no prompt and cannot type any text. Broken:

- platformio-ide-terminal@2.9.4
- platformio-ide-terminal@2.10.0

Older versions (specifically platformio-ide-terminal@2.9.3) work fine.

### Versions

Atom    : 1.33.1 (from `apt-get`)
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.1
python 2.7.12
git 2.7.4

Ubuntu 16.04 LTS

**Comment by casperdcl** [comment] 2019-11-09 22:06
Note that installing atom via `snap` instead (atom 1.41.0) fixes this issue (however `atom --version` and `atom --help` etc now has no output, while `apm --version` works)

**Comment by the-j0k3r** [comment] 2019-11-10 08:11
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/798

Please notice that New versions of the terminal only work with new versions of Atom due to electron version compatibility with node-pty-prebuilt-multiarch read issue #798

Thanks but closing.

**Closed as completed by the-j0k3r** 2019-11-10 08:11 UTC
Labels: duplicate

**Comment by casperdcl** [comment] 2019-11-10 10:16
Thanks; saw there were other closed issues about blank terminals but didn't realise this was a duplicate.
