### ISSUE TITLE
terminal don't allow to write 

### ISSUE THREAD

**Issue by abdullahkhalid092** [platformio/platformio-atom-ide-terminal#515] opened 2018-04-25 11:57 UTC
not working on 32bit  system

**Comment by the-j0k3r** [comment] 2018-05-16 07:39
Try to uninstall and reinstall the platformio-atom-ide-terminal again, if that doesnt work get another terminal -> read https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678

**Comment by the-j0k3r** [comment] 2018-06-01 15:29
duplicate of #500

**Comment by the-j0k3r** [comment] 2018-08-17 09:17
@ivankravets please close this is a duplicate marked as above

**Closed as completed** 2018-08-17 10:33 UTC
Labels: PR welcome
