### ISSUE TITLE
Recent Problem

### ISSUE THREAD

**Issue by claudiacruz85** [platformio/platformio-atom-ide-terminal#484] opened 2018-03-16 15:51 UTC
It is shown, but it does not allow writing, or doing anything. Yesterday was working well.

**Comment by ivankravets** [comment] 2018-03-16 17:39
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/477#issuecomment-373765626

**Closed as completed by ivankravets** 2018-03-16 17:39 UTC
