### ISSUE TITLE
terminal open on focus

### ISSUE THREAD

**Issue by kyuwoo-choi** [platformio/platformio-atom-ide-terminal#494] opened 2018-03-23 20:42 UTC
`platformio-ide-terminal:focus` should open terminal if closed.

**Comment by the-j0k3r** [comment] 2019-02-07 08:40
As far as I can tell this works as intended, to open a terminal when closed its not that command.

Retest with 2.9.0 though dont expect that command to ever open a terminal if closed, it just focus into/out of terminal.

**Closed as completed by the-j0k3r** 2019-02-07 08:40 UTC
Labels: more information required, outdated versions
