### ISSUE TITLE
Error when opening terminal

### ISSUE THREAD

**Issue by Zireael** [platformio/platformio-atom-ide-terminal#701] opened 2019-06-16 21:16 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description
I have upgraded to latest Atom version and getting this error message now:

![image](https://user-images.githubusercontent.com/3856578/59569583-7e901c80-9083-11e9-855c-ddc6ba9b3cdc.png)

### Steps to reproduce

1. Click View -> Terminal -> New Terminal Window

**Expected behavior:** 
Terminal works

**Actual behavior:** 

Terminal does not work.

I'm getting error message inside terminal window:

```
For more info check out the docs: https://nuclide.io/docs/features/terminal
Error starting process:
Error: The specified module could not be found.
\\?\C:\Users\xxx\.atom\packages\atom-ide-ui\node_modules\nuclide-prebuilt-libs\pty\build\pty-node-v64-win32-x64\pty.node
```

**Reproduces how often:**  100%

### Versions

```
> atom --version
Atom    : 1.39.0-beta1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
```
> apm --version
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.0-beta1
python 3.8.0b1
git 2.8.1.windows.1
visual studio 2015
```
OS name and version: Win 10 x64
Platformio-ide-terminal version: 2.9.1

**Comment by the-j0k3r** [comment] 2019-06-17 06:52
duplicate of #700

**Closed as completed by the-j0k3r** 2019-06-17 06:52 UTC
Labels: duplicate
