### ISSUE TITLE
add windows WSL, git bash and bash as terminals

### ISSUE THREAD

**Issue by bobbymac** [platformio/platformio-atom-ide-terminal#552] opened 2018-06-17 14:32 UTC
Would be really cool if you added a few if/else statements  ##for windows wsl-bridge, git-bash, windows bash.

**Comment by the-j0k3r** [comment] 2018-06-22 03:21
See https://github.com/platformio/platformio-atom-ide-terminal/pull/66 that would do it, but alas its 2 years old and not going anywhere.

**Comment by the-j0k3r** [comment] 2019-01-27 07:59
xterm.js would very much solve this instead of using the old term.js which is 100% unmaintained.

**Comment by the-j0k3r** [comment] 2019-02-08 05:57
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/435

**Closed as completed by the-j0k3r** 2019-02-08 05:57 UTC
Labels: duplicate, PR welcome, feature request
