### ISSUE TITLE
No text/cursor in terminal with platform-ide-terminal 2.9.0

### ISSUE THREAD

**Issue by ManuelZ** [platformio/platformio-atom-ide-terminal#650] opened 2019-02-09 22:57 UTC
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

When I open a terminal I get no terminal, nor errors, just a "loading" terminal.

- Deleted .atom folder
- Uninstalled Atom
- Installed Atom 1.34.0
- Installed platform-ide-terminal 2.9.0 via apm

### Steps to reproduce

1. Open Atom
2. Click in the bottom left "+" terminal button

**Expected behavior:** 
- To get a terminal

**Actual behavior:** 
No terminal appears: 
![image](https://user-images.githubusercontent.com/115771/52527134-6e110500-2c91-11e9-808e-a857c0a4e1ee.png)

**Reproduces how often:** 
- All the time

### Versions

```
> atom --version

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

```
```
> apm --version

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.6.6
git 2.15.1.windows.2
visual studio 2015
```
OS name and version: Windows 10 Home 1809
Platformio-ide-terminal version: 2.9.0

### Additional Information

---
### Me too reports

**Anyone else facing this exact issue and posting "me too" reports here, please copy and paste [this](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md) into the reply field and provide the requested information.**

Thank you.

**Comment by the-j0k3r** [comment] 2019-02-10 06:37
Thank you for your ticket.

A few  things I suggest trying.

Disable GPU rendering in Atom.

1) see https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem
  * in an external terminal run the commands above, then restart Atom and retry. 

2) Try with python 2.7 instead of 3.6.6? (node-pty-prebuilt install scripts doesnt suport python 3.x.x
  * uninstall python 3.6.6 install 2.7
  * uninstall platformio-ide-terminal via apm and reinstall via apm.

3) Also if you have a virtual machine to test with Windows 10 pro (just a trial install of the OS will do for testing purposes.)
* Install Atom 1.34.0 and then platformio-ide-terminal 2.9.0 via apm again with python 2.7

Please report back with full results.

**Comment by dunkinman** [comment] 2019-02-10 17:49
Following.  Have same issue.  Seems that falling back to Python 2.7 isn't really practical.  Is the terminal not configured to work with Python 3?

**Comment by the-j0k3r** [comment] 2019-02-10 18:11
>   2. Try with python 2.7 instead of 3.6.6? (node-pty-prebuilt install scripts doesnt suport python 3.x.x

@dunkinman re: python version is about that nugget..

**Comment by dunkinman** [comment] 2019-02-10 18:17
@the-j0k3r So....fall back to python 2.7 and then install and then could upgrade Python to 3.6?  Is this what you're suggesting?  Is it solely the limitation of the install scripts?  So that after they are run upgrading to Python 3.x.x would then work or would this break the installation again?

**Comment by the-j0k3r** [comment] 2019-02-10 18:26
>  Is it solely the limitation of the install scripts?

Yes, Its one of the dependencies called node-gyp (caught at v3.4.0) that has been reported failing with python 3.x.x.

>So that after they are run upgrading to Python 3.x.x would then work or would this break the installation again?

Wouldnt want to guess beofre it happens.

**Comment by dunkinman** [comment] 2019-02-10 18:36
@the-j0k3r But you're running Python 3.5.2....and haven't experienced the problem?

**Comment by the-j0k3r** [comment] 2019-02-10 18:42
Be that as it may, Thats the informant Im extracting from other bug reports. I think we have established Im not the one with these issues.

**Comment by dunkinman** [comment] 2019-02-10 18:45
@the-j0k3r I'm just trying to reconcile the theory and narrow down the culprit.  I read somewhere that  was your version.  I understand you're not having issues.  I thought I read somewhere else that Python 3.4 is a culprit as well.  So bottom line your recommendation is to downgrade Python to 2.7, upgrade to 2.9 and then possibly upgrade Python to 3.x.x and see what happens?

**Comment by the-j0k3r** [comment] 2019-02-10 18:49
Lets not hijack this thread.

**Comment by dunkinman** [comment] 2019-02-10 18:56
@the-j0k3r I'm not hijacking, I'm trying to make sense out of your recommendations and also document them so that I can proceed accordingly and also have it documented for future visitors.  When I reported the issue initially you suggested somehow this issue was limited to just me.  Now more more people are reporting the issue and I'm trying to reconcile what's been determined thus far.  Is the approach that I documented in the last response reasonable in your opinion?

**Comment by jhollowe** [comment] 2019-02-15 16:40
Does platformio-ide-terminal install any extra things outside of the .atom directory? I have tried reinstalling Atom and this on a computer that had older versions of this package, but that did not work. I installed on a computer that I had not installed this package on before and it worked.

Are there any outdated external assets that might need to be deleted also?

**Comment by the-j0k3r** [comment] 2019-02-16 07:06
> Does platformio-ide-terminal install any extra things outside of the .atom directory?

Not that Im aware of, but package installation is done by [apm](https://github.com/atom/apm) platformio-ide-terminal  has nothing to do with this process..
Bare in mind Atom leaves various directories behind location dependent on OS, and your experiment proves that there is something going wrong,in this older machine likely a product of something going awry sometime in the past.

Please delete All Atom/Related created directories and try again, if it persists open a new ticket with required information, its preferable to try and triage things.

**Comment by the-j0k3r** [comment] 2019-03-04 11:13
@ManuelZ a reminder to lets us know the result of suggestions above.

**Comment by the-j0k3r** [comment] 2019-03-08 11:11
Ill close this as duplicate of #668 its where I been merging all duplicates and transplant the issue report to there.

Please use #668 from now on.

**Closed as completed by the-j0k3r** 2019-03-08 11:11 UTC
Labels: duplicate
