### ISSUE TITLE
Open the terminal ,Then occur a messy code

### ISSUE THREAD

**Issue by EngineerFan** [platformio/platformio-atom-ide-terminal#808] opened 2019-11-22 10:15 UTC
<img width="1064" alt="WX20191122-181356@2x" src="https://user-images.githubusercontent.com/26210757/69417650-0fb2a000-0d54-11ea-975a-1c515a14b090.png">

**Comment by EngineerFan** [comment] 2019-11-22 10:17
Atom version info ：  1.41.0  
OS:     Mac OS 10.14.6

**Comment by the-j0k3r** [comment] 2019-11-22 11:30
Howdy try without ANY terminal addons like powerline or whatever you added to the terminal profile to change the prompt.

I can tell you theres no such issue with an unmodified prompt in macOS

What it look like also in your font in usage doesnt have the symbols required by powerline, so use a better font, but while modifiying the prompt, please notice issues are not valid to report against the project, hence marked external.

Also, filling in the issue template isnt optional FYI.

Thanks

**Comment by the-j0k3r** [comment] 2019-12-16 08:47
Also here is a fix! Install `CascadiaPL.ttf` from https://github.com/microsoft/cascadia-code/releases it has native Powerline ligatures which your font reported above does not have.

You will also need to setup the terminal to use this `CascadiaPL.ttf` font, after which the issue should be gone.

However please notice that platformio-ide-terminal may also display other issues with Powerline type input modifiers mostly due to #426 so until there's xterm support nothing will improve in that front.

Any xterm additions are user contributed anyone can contribute [via pr to this project ](https://github.com/platformio/platformio-atom-ide-terminal/compare/master...platformio:master)or to my fork upstream at https://github.com/bus-stop/terminus which is now completely written in JavaScript.

Hope this helps.

**Comment by the-j0k3r** [comment] 2020-03-13 11:02
this is a duplicate of #33 #86 #152 #212

**Closed as completed by the-j0k3r** 2020-03-13 11:02 UTC
Labels: duplicate, wontfix, external, workaround posted
