### ISSUE TITLE
Terminal doesn't work in panels anymore

### ISSUE THREAD

**Issue by davidjorg** [platformio/platformio-atom-ide-terminal#449] opened 2018-01-09 13:32 UTC
Any attempt to move the terminal to a panel by dragging the terminal icon into the tab bar of an existing panel will result in an empty new panel and the corresponding terminal gone. Also, this seems related to the following deprecation error:

`Pane::addItem(item, 2) is deprecated in favor of Pane::addItem(item, {index: 2})`

Moving the terminal to a panel that is not hiding other parts of the window was one of the most useful features.

Using platformio-ide-terminal 2.8.0 and Atom 1.23.1.

**Comment by mediafinger** [comment] 2018-02-27 18:42
A duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/209

**Comment by the-j0k3r** [comment] 2019-02-07 10:05
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Closed as completed by the-j0k3r** 2019-02-07 10:05 UTC
Labels: bug, duplicate

**Comment by the-j0k3r** [comment] 2019-11-15 13:35
fixed in https://github.com/bus-stop/terminus/pull/5
