### ISSUE TITLE
Terminal (2.9.3) not working in Atom (1.39.1 x64)

### ISSUE THREAD

**Issue by evijay** [platformio/platformio-atom-ide-terminal#763] opened 2019-08-08 10:11 UTC
### Unable to working plugin platformio-ide-terminal (2.9.3) on Microsoft Windows [Version 10.0.17134.885]  64 bit platform

```
atom -v
	Atom    : 1.39.1
	Electron: 3.1.10
	Chrome  : 66.0.3359.181
	Node    : 10.2.0

apm -v
	apm  2.2.4
	npm  6.2.0
	node 8.9.3 x64
	atom 1.39.1
	python 2.7.14
	git 2.16.2.windows.1
	visual studio 2015
```
![image](https://user-images.githubusercontent.com/10086696/62694819-b156f100-b9f2-11e9-806f-e8699dcbbe35.png)

**Comment by the-j0k3r** [comment] 2019-08-08 11:55
@evijay see this https://github.com/platformio/platformio-atom-ide-terminal/issues/760#issuecomment-517757440

duplicate of #760

**Closed as completed by the-j0k3r** 2019-08-08 11:55 UTC
Labels: duplicate
