### ISSUE TITLE
platformio-ide-terminal

### ISSUE THREAD

**Issue by MDGMDG** [platformio/platformio-atom-ide-terminal#533] opened 2018-05-19 19:10 UTC
platformio-ide-terminal does not work, the panel shows a black area,but can't enter any text on it.

My OS is Windows 7,and my Atom version 1.27.0

Thanks for your help

MDGMDG

**Comment by ANUJ-07** [comment] 2018-05-20 06:31
Same issue

**Comment by bccrayton** [comment] 2018-05-20 20:12
same issue but I'm on MacOS Sierra and Atom version 1.27.0

**Comment by moremorenoadan** [comment] 2018-05-24 20:43
Just the same for me.

Win 10. Atom 1.27.1

Thanx!

**Comment by the-j0k3r** [comment] 2018-05-27 11:45
Uninstall and reinstall, it works.

**Comment by moremorenoadan** [comment] 2018-05-29 20:42
It was the first thing I did: uninstall & install again, but it doesn't work.

**Comment by the-j0k3r** [comment] 2018-05-29 21:15
Good luck then, this is no longer developed.

**Comment by deepankarbaruah** [comment] 2018-05-31 07:53
Platformio-ide-terminal does not work, the panel shows a black area,but can't enter any text on it.
Windows 7,and Atom version 1.27.1

**Comment by the-j0k3r** [comment] 2018-07-05 14:03
@MDGMDG @moremorenoadan is this still an issue with Atom 1.28.0 and platformio-ide-terminal 2.8.3?

**Comment by the-j0k3r** [comment] 2018-07-05 14:17
also this is a duplicate of #500 

@ivankravets please add a duplicate label and if possible a feedback requested label, pending feedback maybe closed at your discretion.

**Closed as completed** 2018-07-05 20:36 UTC
Labels: duplicate
