### ISSUE TITLE
How to with iterm2 - Powerline font

### ISSUE THREAD

**Issue by mardianto** [platformio/platformio-atom-ide-terminal#152] opened 2017-01-19 18:59 UTC
how You can configure font and colors through the package settings.
this on iterm2
![screen shot 2017-01-20 at 01 54 01](https://cloud.githubusercontent.com/assets/5848383/22120785/cd11da94-deb3-11e6-83de-152c81ca3c9e.png)

and this on atom 
![screen shot 2017-01-20 at 01 56 30](https://cloud.githubusercontent.com/assets/5848383/22120787/cdd55848-deb3-11e6-9ab9-ebfbc210dbb3.png)

thanks,
Regads

Mardianto

**Comment by mikeerickson** [comment] 2017-01-21 22:26
Works just fine for me... Have you set the font correct (should be Powerline)

![atom-agnoster](https://cloud.githubusercontent.com/assets/183153/22178215/9fe759da-dfe5-11e6-9929-00ff70d7d8d7.png)

**Comment by mardianto** [comment] 2017-01-22 02:32
u have tutorial for setup this, mikeerickson?

**Comment by ttuygun** [comment] 2017-08-15 19:25
@mardianto just set `Meslo LG L DZ for Powerline` in Font Family

**Comment by AlanGabbianelli** [comment] 2017-08-20 18:24
Thanks @ttuygun, that solved it for me.
I was trying to use `Meslo LG M Regular for Powerline` (as in my iTerm2 settings), but that didn't work. Do you have any idea why?

**Comment by ttuygun** [comment] 2017-08-20 20:54
@AlanGabbianelli did you install the font file to the system?

**Comment by AlanGabbianelli** [comment] 2017-08-20 21:12
@ttuygun yes, the font is installed.
The problem was the extra `Regular` that I wrote. I got it working just setting it to `Meslo LG M for Powerline`, instead of `Meslo LG M Regular for Powerline`.
I had initially copied it from my iTerm2 setting, but it turns out only the font family is needed, not the  font typeface.

**Comment by the-j0k3r** [comment] 2019-12-16 08:49
Also here is a fix! Install `CascadiaPL.ttf` from https://github.com/microsoft/cascadia-code/releases it has native Powerline ligatures which your font reported above does not have.

You will also need to setup the terminal to use this `CascadiaPL.ttf` font, after which the issue should be gone.

However please notice that platformio-ide-terminal may also display other issues with Powerline type input modifiers mostly due to #426 so until there's xterm support nothing will improve in that front.

Any xterm additions are user contributed anyone can contribute [via pr to this project ](https://github.com/platformio/platformio-atom-ide-terminal/compare/master...platformio:master)or to my fork upstream at https://github.com/bus-stop/terminus which is now completely written in JavaScript.

Hope this helps.

**Comment by shinusuresh** [comment] 2020-02-04 11:23
`MesloLGS NF` worked for me

**Comment by the-j0k3r** [comment] 2020-03-13 11:06
duplicate of #33 #86

**Closed as completed by the-j0k3r** 2020-03-13 11:06 UTC
Labels: duplicate, question, external
