### ISSUE TITLE
Terminal is not responding blinking cursor on blank page

### ISSUE THREAD

**Issue by ImAbhi94** [platformio/platformio-atom-ide-terminal#806] opened 2019-11-13 16:25 UTC
### Description

Hi, 

My terminal is not responding, as I installed platformio-ide-terminal and restart atom it's blinking cursor on a blank page, nothing is coming.

**Expected behavior:** 
There should be a folder path coming.

**Actual behavior:** 
there is only a blank page.

### Version```
> atom --version

1.40.1.0
```
> apm --version

OS name and version: windows 10
Platformio-ide-terminal version: downloaded from Atom installer.

**Comment by the-j0k3r** [comment] 2019-11-13 16:28
Uninstall and reinstall platforio-ide-terminal

Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.

**Comment by the-j0k3r** [comment] 2019-11-13 16:38
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/668

read https://github.com/platformio/platformio-atom-ide-terminal/issues/668#issuecomment-546580232

**Closed** 2019-11-13 16:38 UTC
Labels: invalid
