### ISSUE TITLE
Installing “platformio-ide-terminal@2.9.1” failed

### ISSUE THREAD

**Issue by iamParvezKhan25** [platformio/platformio-atom-ide-terminal#712] opened 2019-07-24 11:45 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

### Additional Information

![atomTerminalBug](https://user-images.githubusercontent.com/41503632/61791040-73749d00-ae36-11e9-9780-445443702927.png)

**Comment by the-j0k3r** [comment] 2019-07-24 11:57
duplicate of #700

**Closed as completed** 2019-07-24 11:57 UTC
Labels: duplicate
