### ISSUE TITLE
Problems installing platformio-ide-terminal

### ISSUE THREAD

**Issue by Arron11** [platformio/platformio-atom-ide-terminal#723] opened 2019-07-25 02:26 UTC
- [x ] I have reset Atom to defaults prior to submitting report.
- [x ] I have not reset Atom to defaults prior to submitting report.
### Description

Problems installing the platformio-ide-terminal. It was working fine, then all of a sudden it stopped working.

### Steps to reproduce

1. I was using atom as usual and all of a sudden an error poped up. 
2.I tried to uninstall and re install but it wont install anymore.
3.

**Expected behavior:** 
work as designed

**Actual behavior:** 
Not work

**Reproduces how often:** 
100%

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:Windows 10
Platformio-ide-terminal version: 2.9.1

### Additional Information

nstalling “platformio-ide-terminal@2.9.1” failed.Hide output…

> node-pty-prebuilt@0.7.6 install C:\Users\azza1\AppData\Local\Temp\apm-install-dir-119625-14984-1jo69ir.q789\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js

C:\Users\azza1\AppData\Local\Temp\apm-install-dir-119625-14984-1jo69ir.q789\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\azza1\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\azza1\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\azza1\AppData\Local\Temp\apm-install-dir-119625-14984-1jo69ir.q789\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\azza1\AppData\Local\Temp\apm-install-dir-119625-14984-1jo69ir.q789\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt\build\binding.sln]

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\azza1\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\azza1\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\azza1\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\azza1\AppData\Local\Temp\apm-install-dir-119625-14984-1jo69ir.q789\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\azza1\AppData\Local\Temp\apm-install-dir-119625-14984-1jo69ir.q789\package.json'
npm WARN apm-install-dir-119625-14984-1jo69ir.q789 No description
npm WARN apm-install-dir-119625-14984-1jo69ir.q789 No repository field.
npm WARN apm-install-dir-119625-14984-1jo69ir.q789 No README data
npm WARN apm-install-dir-119625-14984-1jo69ir.q789 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\azza1\.atom\.apm\_logs\2019-07-25T02_08_55_896Z-debug.log

**Comment by the-j0k3r** [comment] 2019-07-25 05:56
@Arron11 thanks for bring this issue to our attention.

This is a duplicate of #700 see https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround

**Closed as completed by the-j0k3r** 2019-07-25 05:56 UTC
Labels: duplicate
