### ISSUE TITLE
Failed to activate the platformio-ide-terminal package

### ISSUE THREAD

**Issue by Mohammad-Ha** [platformio/platformio-atom-ide-terminal#714] opened 2019-07-24 15:42 UTC
[Enter steps to reproduce:]

1. Install the package from Atom's packages manager.

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.9.1

What I tried: 
- Reinstalling the package.
- Uninstalling Atom completely.

### Stack Trace

Failed to activate the platformio-ide-terminal package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'pio-terminal-status-icon'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'pio-terminal-status-icon'. A type with that name is already registered.
    at /packages/platformio-ide-terminal/lib/status-icon.coffee:100:27)
    at /packages/platformio-ide-terminal/lib/status-icon.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/status-icon.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:147410)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:146719)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:5:14)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:147410)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:146719)
    at Object.consumeStatusBar (/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:27)
    at Provider.provide (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:14:1124320)
    at ServiceHub.consume (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3537050)
    at Package.activateServices (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3545282)
    at Package.activateNow (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:3542037)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:1208969)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:381902)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:381864)
    at ~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:935623
    at r (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:930229)
    at n (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:14:1127227)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:14:1127433)
    at ChildProcess.emit (events.js:182:13)
```

### Commands

```
     -1:20.4.0 intentions:highlight (input.hidden-input)
     -1:20.3.0 core:close (input.hidden-input)
  3x -1:06.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
color-picker 2.3.0 
ide-php undefined 
intentions 1.1.5 
language-blade 0.43.1 
language-vue 0.24.0 
laravel 0.7.1 
lint-sass-vue 1.0.5 
linter 2.3.0 
linter-php 1.6.1 
linter-ui-default 1.7.1 
php-cs-fixer 4.1.1 
php-fmt 0.1.2 
php-hyperclick 1.2.1 
platformio-ide-terminal 2.9.1 
todo-show 2.3.2 
```

**Comment by the-j0k3r** [comment] 2019-07-24 17:26
@Mohammad-Ha thanks for bring this issue to our attention.

This is a duplicate of #700 see https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround

Finally one duplicate issue that actually properly reported, for that thanks.

**Closed as completed by the-j0k3r** 2019-07-24 17:26 UTC
Labels: duplicate
