### ISSUE TITLE
Can't open platformio terminal

### ISSUE THREAD

**Issue by anm9487** [platformio/platformio-atom-ide-terminal#586] opened 2018-08-17 00:33 UTC
I've attempted to uninstall and reinstall both atom and platformio but still no luck. Every time I try to open the terminal I get the error attached.
![atom failure](https://user-images.githubusercontent.com/42454922/44241706-99f47780-a193-11e8-838f-b21a29474b09.PNG)

**Comment by the-j0k3r** [comment] 2018-08-17 07:54
read https://github.com/platformio/platformio-atom-ide-terminal/issues/584

**Comment by the-j0k3r** [comment] 2018-08-17 09:09
@ivankravets please close this is a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/584

**Closed as completed** 2018-08-17 10:33 UTC
