### ISSUE TITLE
this '+' of ide-terminal disappeared

### ISSUE THREAD

**Issue by Rui471855634** [platformio/platformio-atom-ide-terminal#724] opened 2019-07-25 03:07 UTC
- [x]  I have reset Atom to defaults prior to submitting report.
- [x]  I have not reset Atom to defaults prior to submitting report.
### Description
When I opened atom,the '+' button disappeared.Then I reinstalled platformio-ide-terminal,and try to toggle that.It still doesnt appear
![image](https://user-images.githubusercontent.com/13493551/61842910-6acea600-aecc-11e9-8fec-f4fb818762f6.png)

### Versions

```
> atom --version
1.39.0
```
```
> apm --version
2.2.4
```
OS name and version: Windows 10
Platformio-ide-terminal version:2.9.1

**Comment by the-j0k3r** [comment] 2019-07-25 05:55
@AlanOzil thanks for bring this issue to our attention.

This is a duplicate of #700 see https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround

**Closed as completed by the-j0k3r** 2019-07-25 05:55 UTC
Labels: duplicate
