### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by VladimirtheGreatest** [platformio/platformio-atom-ide-terminal#710] opened 2019-07-24 10:45 UTC
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Early in the morning I received a message that my current version of platformio-atom-ide is not compatible package. I tried to rebuild the package but I received an error, so I uninstalled the package and installed completely new version of node.js and atom as well. I tried to install platformio again but this time every time I click install it does not install itself and also I am not getting any error messages, it is really weird. 

**Expected behavior:** 
I clicked install and I would expect to get a message or an error.

**Actual behavior:** 
I clicked install and after few seconds of installing the install button just reloads again and nothing happens

> atom --version 1.39.0

OS name and version: Windows 10, 64bit
Platformio-ide-terminal version: 2.9.1

**Comment by the-j0k3r** [comment] 2019-07-24 11:59
@VladimirtheGreatest thanks for bring this issue to our attention.

This is a duplicate of #700 cant do anything about that Im afraid.

**Closed as completed by the-j0k3r** 2019-07-24 11:59 UTC
Labels: duplicate
