### ISSUE TITLE
Error - Electron 4.2.7 Atom Version 1.42.0-nightly0 x64

### ISSUE THREAD

**Issue by ianindratama** [platformio/platformio-atom-ide-terminal#766] opened 2019-08-11 11:32 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.Install the Package
2.
3.

**Expected behavior:** Installed so i can use it

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/53966296/62833211-a8258880-bc6d-11e9-8fe5-2011202dc77d.png)

**Reproduces how often:** EveryTime

### Versions

```
> atom 1.42.0-nightly0 x64

```
```
> Node  v10.11.0

```
OS name and version: Windows 10
Platformio-ide-terminal version:  platformio-ide-terminal@2.9.4

**Comment by the-j0k3r** [comment] 2019-08-11 12:22
Thank you for opening an issue report.

Please try stable Atom release. If you read error it becomes clear. Alternatively you will need to rebuild binaries by following this https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 if you wish to remain with unstable builds of Atom.

thanks for your understanding.

@oznu I thought `0.9.0-beta21.legacy` also supported 4.x Eltron builds, or isnt 4.2.7 any of these?

**Comment by ianindratama** [comment] 2019-08-11 19:32
@the-j0k3r i have followed the instructions from https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 but somehow it still didnt work
Here is the Screenshot from the error after i tried to install the package again with the instructions from https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895
![image](https://user-images.githubusercontent.com/53966296/62838629-aaa9d180-bcb1-11e9-8d85-7ad7217c2329.png)
![image](https://user-images.githubusercontent.com/53966296/62838634-b4cbd000-bcb1-11e9-8700-1f89765b3575.png)

![image](https://user-images.githubusercontent.com/53966296/62838634-b4cbd000-bcb1-11e9-8700-1f89765b3575.png)

**Comment by the-j0k3r** [comment] 2019-08-12 05:59
Well, If that didnt work Ive no idea what to suggest except downgrade to stable version of Atom.

Technically the node-pty-prebuilt-multiarch build binaries for Electron 4.0.0 and 4.0.4 Ive no idea why with Electron 4.2.7 doesnt work Ive already pinged @oznu to see what he says about this.

**Comment by the-j0k3r** [comment] 2019-08-13 13:38
@ianindratama this is strange @alejandroastudillo commneted in https://github.com/platformio/platformio-atom-ide-terminal/issues/769#issuecomment-520788777 that he sucessufuly instaled this package with the Atom nightly,

Maybe you want to upgrade your nightly and try or downgrade it. Having two users state separate things about the same topic makes ones mind wonder.

**Comment by the-j0k3r** [comment] 2019-08-13 13:43
@oznu Atom nightlies in Linux the prebuilt binaries work, seems Windows is doing something weird in this case.

**Comment by LeCyberDucky** [comment] 2019-08-13 17:15
@the-j0k3r I am experiencing the same issue with stable Atom 1.40.0.

**Comment by YangFei1990** [comment] 2019-08-13 19:02
+1 can't install in Atom 1.40.0
![Screen Shot 2019-08-13 at 12 02 16 PM](https://user-images.githubusercontent.com/33940270/62969507-3c086900-bdc2-11e9-8424-991311333fe6.png)

**Comment by the-j0k3r** [comment] 2019-08-14 07:00
@YangFei1990 @LeCyberDucky 

Uninstall platformio-ide-terminal and reinstall.

1.  Uninstall platformio-ide-terminal via `apm uninstall platformio-ide-terminal` 
2. Make sure its gone from `.atom/packages` directory in your user folder, and reinstall it
   `apm i platformio-ide-terminal@2.9.4`.

 Windows/macOS/Linux work with electron 3.x Works perfectly fine, Atom 1.40.0 and Atom 1.39.1 use same electron version.

**Comment by the-j0k3r** [comment] 2019-08-14 07:05
Related issue for **nightlies** aka electron 4.2.7 https://github.com/oznu/node-pty-prebuilt-multiarch/issues/7, please make your comments there.

If your version of electron is 3.x dont make any comments in that issue ticket. Whatever is happening is unrelated.

**Comment by the-j0k3r** [comment] 2019-08-14 17:51
@LeCyberDucky @YangFei1990 one of you open a new issue ticket and fil in all issue template fields., this topic is for electron 4.x only.

FYI: I have tested platformio-ide-terminal@2.9.4 with Atom 1.39.1 and 1.40.0 and it works on all platforms.

Thanks for your understanding.

**Comment by the-j0k3r** [comment] 2019-08-17 16:57
See https://github.com/atom/atom/issues/19780 could very well be the cause.

**Comment by UziTech** [comment] 2019-08-20 18:45
@the-j0k3r https://github.com/atom/apm/pull/862 was definitely the issue. After installing atom v1.41.0-beta1 and doing an `apm rebuild` with that merged it works great

**Comment by the-j0k3r** [comment] 2019-08-21 05:15
Upgrade your nightly this has been fixed upstream.

**Closed as completed by the-j0k3r** 2019-08-21 05:15 UTC
Labels: external, more information required
