### ISSUE TITLE
Fullscreen toggle seems broken with Atom 1.17.0

### ISSUE THREAD

**Issue by satishmohan** [platformio/platformio-atom-ide-terminal#227] opened 2017-05-16 18:29 UTC
After upgrading to Atom 1.17.0, the fullscreen toggle button seems to be behaving weirdly. It shows the screen split into two panes.

Thanks
Satish

**Comment by satishmohan** [comment] 2017-05-16 22:54
Is there an issue with $('.item-views').height() ?
```
  maximize: ->
    @subscriptions.remove @maximizeBtn.tooltip
    @maximizeBtn.tooltip.dispose()
 
    @maxHeight = @prevHeight + $('.item-views').height()
    btn = @maximizeBtn.children('span')
    @onTransitionEnd => @focus()
 
    if @maximized
      @maximizeBtn.tooltip = atom.tooltips.add @maximizeBtn,
        title: 'Fullscreen'
      @subscriptions.add @maximizeBtn.tooltip

      @adjustHeight @prevHeight
      btn.removeClass('icon-screen-normal').addClass('icon-screen-full')
      @maximized = false
    else
      @maximizeBtn.tooltip = atom.tooltips.add @maximizeBtn,
        title: 'Normal'
      @subscriptions.add @maximizeBtn.tooltip
      @adjustHeight @maxHeight
      btn.removeClass('icon-screen-full').addClass('icon-screen-normal')
      @maximized = true
 ```

**Comment by ivankravets** [comment] 2017-05-16 22:59
What is your OS? I can't reproduce this issue.

**Comment by satishmohan** [comment] 2017-05-16 23:01
I'm on macOs Sierra 10.12.4

**Comment by satishmohan** [comment] 2017-05-17 00:29
Here's an example of what I'm talking about - after I hit the fullscreen toggle button - the screen gets mirrored into two parts - overwriting the vertical tab bars on Atom:
![split-screen](https://cloud.githubusercontent.com/assets/2322735/26133581/0b0bc22e-3a5d-11e7-9f8c-219180c0f41d.png)

**Comment by satishmohan** [comment] 2017-05-17 05:11
I was able to narrow it down a bit further - the split screen happens only when the output of a command fills up the screen - for example try running `top` within the terminal window. If I quit the top process, the window output becomes normal again. Seems like sizing issue...?

**Comment by satishmohan** [comment] 2017-05-19 15:07
Is anybody else running into this issue? This was working perfectly with Atom 1.16...

**Comment by ivankravets** [comment] 2017-05-19 15:46
I've received this issue today. It looks that when you change a height of window, that this issue comes. Try to close all windows, open new terminal and press maximaze. Does it work now?

**Comment by satishmohan** [comment] 2017-05-19 17:44
No, I get the same issue. Try running "top" command when the terminal is maximized - it messes up the output.

Would it be possible to get a fix? I had this maximize button mapped to a keyboard shortcut and it was super handy :-)

**Comment by Fred-Barclay** [comment] 2017-05-20 21:30
@satishmohan As a temporary workaround, you should be able to drag the terminal icon from the bottom panel up to your tabs and use it as a fullscreen tab. 

Hope this helps!

**Comment by ivankravets** [comment] 2017-05-20 22:38
Could you try v2.5.1 (just released)?

**Comment by satishmohan** [comment] 2017-05-21 00:28
Hi I tried v2.5.1 - thanks for the update - but still see the issue.

How to reproduce: open a terminal (Cmd+Shift+T), run "top" inside the terminal shell - this will cause the terminal output to overwrite the whole atom screen.

Regards!

**Comment by seajean** [comment] 2017-05-23 09:26
@ivankravets  seems open terminal from the selected directory has broken too.

**Comment by gkid** [comment] 2017-07-05 16:19
I am experiencing the same thing.
It looks as if when the terminal is in full screen - the size of the terminal is larger than the window (is extends past the bottom of the Atom window.
If instead of running 'top' while in full screen, you manually type lines until you reach the bottom of the window, you can see that the last line of text is actually underneath Atom's status bar. Once you enter yet another new line - the terminal window becomes mangled.
I can try to post some screenshots if it can help.

**Comment by satishmohan** [comment] 2017-07-05 16:53
Yes that's correct - I see the same behavior.... Would this be too hard to
fix? I'm guessing its some size calculation somewhere which has broken now
in the newer Atom releases?

**Comment by finferflu** [comment] 2017-08-09 14:48
This is still true with Atom 1.19. And it happens even when there's simply a long history of command, i.e. it's not related to any running command. It does **not** happen with new, just-created terminals.

**Comment by takumiabe** [comment] 2017-09-01 06:00
In my case,
`$('.item-views')` returns 4 elements, and `$('.item-views').height()` returns first element's height.

I try `$('.item-views').has('atom-text-editor').height()` in atom dev-mode, but it fixed only partially:
if `<atom-text-editor />` doesnt exists, it causes error.

`<atom-text-editor />` exists only if the file is opened. so if user closed the file, `height()` return any valid value.

I think `.item-views` is not fit to calculate maxheight of atom's main area.
I'm new man of atom plugin development, so I cannot progress anymore... needs help.

**Comment by Devligue** [comment] 2017-09-05 11:44
I am experiencing the same issue in atom 1.19.5

**Comment by ivankravets** [comment] 2017-09-25 16:19
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/pull/369

**Closed as completed by ivankravets** 2017-09-25 16:19 UTC
Labels: bug, PR welcome
