### ISSUE TITLE
Dont Work 

### ISSUE THREAD

**Issue by CarlosPomboCerroAtos** [platformio/platformio-atom-ide-terminal#582] opened 2018-08-02 09:16 UTC
Assetio failed

expression pc != nullptr

**Comment by the-j0k3r** [comment] 2018-08-11 12:30
@carlospombo Thank you for your first ever report.

In a terminal outside of atom run and paste the output of 

`apm ls`
`atom --version`
`apm --version`

Also please provide screenshots of issue as supporting information.

Also please read #543

**Comment by the-j0k3r** [comment] 2018-08-17 09:11
@ivankravets please close duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/584

**Closed as completed** 2018-08-17 10:33 UTC
