### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by e3bble** [platformio/platformio-atom-ide-terminal#699] opened 2019-06-13 15:11 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Linux Mint
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /home/x/.atom/packages/platformio-ide-terminal/lib/view.coffee:426

TypeError: Cannot read property 'element' of undefined
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.adjustHeight (/packages/platformio-ide-terminal/lib/view.coffee:426:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.maximize (/packages/platformio-ide-terminal/lib/view.coffee:203:8)
    at /packages/autocomplete-clang/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/autocomplete-clang/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/autocomplete-clang/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:28 editor:copy-path (div.terminal)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-live-server 2.3.0 
autocomplete 0.47.0 
autocomplete-clang 0.11.5 
autocomplete-python 1.14.0 
build 0.70.0 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.33 
git-plus 8.6.3 
highlight-selected 0.16.0 
intentions 1.1.5 
language-ini 1.21.0 
linter 2.3.0 
linter-flake8 2.4.0 
linter-gcc 0.7.1 
linter-php 1.6.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
php-server 0.8.0 
pigments 0.40.2 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
python-autopep8 0.1.3 
script 3.18.1 
simple-drag-drop-text 0.4.0 
tool-bar 1.1.11 
```

**Comment by the-j0k3r** [comment] 2019-06-14 06:53
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/689

please read https://github.com/platformio/platformio-atom-ide-terminal/issues/689#issuecomment-493359722

Also you have not filled in the issue template, so there is even less useful information here reported.

**Closed as completed by the-j0k3r** 2019-06-14 06:53 UTC
Labels: duplicate, invalid, unable to duplicate
