### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#569] opened 2018-07-09 19:53 UTC
The cursor just blinks

**Comment by the-j0k3r** [comment] 2018-07-10 07:51
Atom version?
Platformio-ide-terminal version?

Would you press some more keys on your keyboard to describe the stages/steps what you did until you noticed this?

**Comment by the-j0k3r** [comment] 2018-08-17 09:17
@ivankravets duplicate of #500 please close.

**Closed as completed** 2018-08-17 10:33 UTC
