### ISSUE TITLE
Terminal Not Working

### ISSUE THREAD

**Issue by mathannagarajan** [platformio/platformio-atom-ide-terminal#859] opened 2020-05-08 05:21 UTC
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

I didnt find the command line its empty  
![Screenshot_2020-05-08_10-42-47](https://user-images.githubusercontent.com/50189399/81372801-dc54a980-9118-11ea-9818-2bc0ab027005.png)

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version 1.35 .1*86

```
```
> apm --version

```
OS name and version: linux 5.5.0-kali1-amd64
Platformio-ide-terminal version: 2.10.0

**Comment by Vagrantin** [comment] 2020-06-17 09:01
Looks like duplicate of #668

**Comment by the-j0k3r** [comment] 2020-07-15 12:45
Try https://github.com/bus-stop/terminus

**Closed as completed by the-j0k3r** 2020-07-15 12:45 UTC
