### ISSUE TITLE
Terminal opening in a new window instead of inside Atom

### ISSUE THREAD

**Issue by timconnorz** [platformio/platformio-atom-ide-terminal#796] opened 2019-10-15 23:41 UTC
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

When I run 'platformio-ide-terminal:new', it opens the terminal in a new window - not inside of Atom. 

### Steps to reproduce

1. Open Atom (default settings, freshly installed platformio-ide-terminal package
2. Navigate to my file.js
3. Run 'platformio-ide-terminal:new' by pressing alt-shift-T or by using Ctrl-Shift-P and typing it in.

**Expected behavior:** 
I expected the terminal to open inside of atom like it normally does. This way I can type in text to the command line while viewing the file I'm working with, all in the same window.

**Actual behavior:** 
The terminal slides up from the bottom of the Atom window, and then Powershell opens up a new window in front of Atom, inside of the same project folder.

**Reproduces how often:** 
100%

### Versions

```
> atom --version
1.40.1
```
```
> apm --version
2.4.3
```
OS name and version:
Platformio-ide-terminal version:
2.9.4

### Additional Information

I also have installed:
npm 6.2.0
node 10.2.0

**Comment by the-j0k3r** [comment] 2019-10-16 04:32
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/780

@timconnorz see that report, You also give no deatils of OS and if you have recently upgrade OS which is likely cause.

Thanks.

**Comment by CodeArtificial** [comment] 2019-10-16 12:52
I also experienced the same problem when I tried to override the Winpy command prompt. I had tried to search on the issues page to see how I can fix this, but still no solution. 

![image](https://user-images.githubusercontent.com/56638985/66920878-596de380-f04e-11e9-9bb1-088f5a699464.png)

The program is 2.9.4
Atom is 1.40.1

**Comment by the-j0k3r** [comment] 2019-10-16 14:26
@CodeArtificial 

The only known cause for that issue is https://github.com/platformio/platformio-atom-ide-terminal/issues/780 being the Windows 10 upgrade to 1903.

If thats not the issue, [fill in issue template](https://github.com/platformio/platformio-atom-ide-terminal/blob/master/.github/ISSUE_TEMPLATE.md) and post it inline on  #https://github.com/platformio/platformio-atom-ide-terminal/issues/780

I'll close this ticket in favor of https://github.com/platformio/platformio-atom-ide-terminal/issues/780 and open that up for discussion. Clearly a Deluge is about to come.

Thanks

**Closed as completed by the-j0k3r** 2019-10-16 14:26 UTC
Labels: duplicate, wontfix, external

**Comment by timconnorz** [comment] 2019-10-16 17:52
Thanks a ton, i did upgrade OS recently. I'll check out that 780
