### ISSUE TITLE
platformio-ide-terminal issue

### ISSUE THREAD

**Issue by vishaldeep24** [platformio/platformio-atom-ide-terminal#671] opened 2019-03-07 17:42 UTC
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description
I installed platformio-ide-terminal and restarted atom but no terminal is coming up. Neither powershell or cmd is coming up. i uninstalled the package and resinstalled it again still nothing worked.
Just a cusor is blinking if you press any key nothing happens.

### Steps to reproduce
1. open Atom
2. Install platformio-ide-terminal package
3. Try opening the terminal

**Expected behavior:** 
Powershell terminal should start.

**Actual behavior:** 
Nothing happens but a white cursor keeps blinking.

**Reproduces how often:** 
Everytime same thing happens.

### Versions
> atom --version
atom 1.34.0 x64
```
```
> apm --version
apm 2.1.3
```
OS name and version: Windows 10 Home 64-bits
Platformio-ide-terminal version: 2.9.1


### Additional Information
Screenshot of issue attached
![capture](https://user-images.githubusercontent.com/33950336/53976775-af2ff400-412d-11e9-9d4a-ed845d235574.PNG)

**Comment by the-j0k3r** [comment] 2019-03-08 07:57
duplicate of #668 

also missing the actuall full output of the version commands.

@vishaldeep24 please try what https://github.com/platformio/platformio-atom-ide-terminal/issues/668#issuecomment-470396394 suggests.

From now on please make updates in #668

**Closed as completed by the-j0k3r** 2019-03-08 07:57 UTC
Labels: duplicate
