### ISSUE TITLE
terminal not working in atom

### ISSUE THREAD

**Issue by qeithva** [platformio/platformio-atom-ide-terminal#669] opened 2019-03-04 13:56 UTC
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

clean atom install + platformio-ide-terminal
press + sign to open terminal
terminal never comes back to prompt but remains blinking
cmd and powershell are working normally on its own

### Steps to reproduce

1. install AtomSetup-x64.exe
2. install plaformio-ide-terminal 
3.press + sign

**Expected behavior:** 
prompt should occur either powershell or cmd

**Actual behavior:** 
prompt never comes 
only blinking cursor

**Reproduces how often:** 
>10X
100% each time not working

### Versions

C:\Users\Owner>apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.5.2
git 2.16.2.windows.1
visual studio

C:\Users\Owner>atom --version

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

> apm --version

OS name and version:

windows 10 home (1803)

Platformio-ide-terminal version:  2-9-1

### Additional Information

tried to delete .atom many times 
no luck

**Comment by the-j0k3r** [comment] 2019-03-05 09:42
Thank you for your ticket.

As it turns out, this is a duplicate of #668, I have transplanted your issue report to that ticket to keep tickets together that belong together. Apologies for any confusion.

Please refer to #668 from now on.

**Closed as completed by the-j0k3r** 2019-03-05 09:42 UTC
Labels: duplicate
