### ISSUE TITLE
help me out 

### ISSUE THREAD

**Issue by manthanumehta** [platformio/platformio-atom-ide-terminal#715] opened 2019-07-24 16:08 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment] 2019-07-24 17:23
@manthanumehta thanks for bring this issue to our attention.

This is a duplicate of #700 see https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround

Also I dont apprecciate reports that ignore the issue template, even if in this case its a known issue.

**Closed as completed by the-j0k3r** 2019-07-24 17:23 UTC
Labels: duplicate, invalid
