### ISSUE TITLE
Keep terminal tabs upon closing and reopening project

### ISSUE THREAD

**Issue by 7ammer** [platformio/platformio-atom-ide-terminal#56] opened 2016-07-07 18:22 UTC
Currently when I close atom and reopen it I loose all my terminal windows. It would be nice to not have to restart all my terminal windows and rename them all each time I reopen a project.

**Comment by viki53** [comment] 2016-07-22 08:02
Duplicate of #3 I think…

**Closed as completed** 2019-02-06 10:07 UTC
Labels: duplicate
