### ISSUE TITLE
Terminal does not working

### ISSUE THREAD

**Issue by 16273849** [platformio/platformio-atom-ide-terminal#670] opened 2019-03-07 05:47 UTC
![annotation 2019-03-07 134518](https://user-images.githubusercontent.com/41985088/53934887-56d20580-40df-11e9-8f38-bddab6d58b4b.jpg)

- [ x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

After installing the package, I try to open the terminal, the terminal shows up, but cannot type in anything. Also the terminal does not pointing to any file or folder.
Atom version: 1.34.0
platformio-atom-ide-terminal version: 2.9.1

### Steps to reproduce

1. install
2. open Atom, and file
3. click on the + sign on bottom left corner
4. terminal pops up
5. try to type in, nothing happens

**Expected behavior:** 
can type in, can change dir, can run like normal cmd terminal.

**Actual behavior:** 
just a black panal

**Reproduces how often:** 
since after install

### Versions
2.9.1
window 10
```
> atom --version
1.34.0
```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

### Additional Information

![annotation 2019-03-07 134518](https://user-images.githubusercontent.com/41985088/53934924-78cb8800-40df-11e9-8add-5e2cd99f5d33.jpg)

**Comment by PrathyushTuraga** [comment] 2019-03-07 05:59
Right click on console window -> click "clear"
close and re-open terminal session. It worked for me!

**Comment by the-j0k3r** [comment] 2019-03-07 06:35
duplicate of #668 closing.

**Closed as completed by the-j0k3r** 2019-03-07 06:35 UTC
Labels: duplicate
