### ISSUE TITLE
Problem installing package platformio-ide-terminal

### ISSUE THREAD

**Issue by shubhra-singh** [platformio/platformio-atom-ide-terminal#693] opened 2019-05-23 23:14 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment] 2019-05-24 05:19
@shubhra-singh skipping the issue template and leaving it blank is not actionable issue ticket and leaves only but a guess, so I guess this is a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/637 and close this issue as such.

Any installation issues [are to be reported to apm](https://github.com/atom/apm/issues/new) platformio-ide-terminal cannot control apm which is responsible for installs of all atom plugins and their dependencies anyway, so thanks in advance. Thanks.

**Closed as completed by the-j0k3r** 2019-05-24 05:19 UTC
Labels: duplicate, wontfix, external
