### ISSUE TITLE
Installing “platformio-ide-terminal@2.9.4” failed

### ISSUE THREAD

**Issue by shokan** [platformio/platformio-atom-ide-terminal#772] opened 2019-08-16 17:28 UTC
- [x] I have reset Atom to defaults prior to submitting report.
- [] I have not reset Atom to defaults prior to submitting report.
### Description

cannot install the platformio-ide-terminal plugin

### Steps to reproduce

1. Go to: Atom -> Preferences -> Install -> 
2. Choose: platformio-ide-terminal 
3. 

**Expected behavior:** 
Get access to the terminal 

**Actual behavior:** 
```log
Installing “platformio-ide-terminal@2.9.4” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /private/var/folders/5l/bkxy55qx31zbyh47t9b76n800000gn/T/apm-install-dir-119716-1038-k1fhe3.jy0ud/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=darwin)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:282:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/5l/bkxy55qx31zbyh47t9b76n800000gn/T/apm-install-dir-119716-1038-k1fhe3.jy0ud/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/5l/bkxy55qx31zbyh47t9b76n800000gn/T/apm-install-dir-119716-1038-k1fhe3.jy0ud/package.json'
npm WARN apm-install-dir-119716-1038-k1fhe3.jy0ud No description
npm WARN apm-install-dir-119716-1038-k1fhe3.jy0ud No repository field.
npm WARN apm-install-dir-119716-1038-k1fhe3.jy0ud No README data
npm WARN apm-install-dir-119716-1038-k1fhe3.jy0ud No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shokan/.atom/.apm/_logs/2019-08-16T17_20_45_725Z-debug.log
```

**Reproduces how often:** 

### Versions

```
> atom --version
Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
```
> apm --version

apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0
python 3.7.1
git 2.15.0

```
OS name and version:
MacOs Mojave
10.14.5
Platformio-ide-terminal version:
2.9.4

**Comment by the-j0k3r** [comment] 2019-08-17 06:48
This works see https://github.com/platformio/platformio-atom-ide-terminal/issues/770#issuecomment-521368518 for proof and is also a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/770

Theres things to try in  https://github.com/platformio/platformio-atom-ide-terminal/issues/770#issuecomment-521934410

**Closed as completed by the-j0k3r** 2019-08-17 06:48 UTC
Labels: duplicate, unable to duplicate, macos

**Comment by the-j0k3r** [comment] 2019-08-17 08:50
also re:

>gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.7.1, which is not supported by gyp.

try with python 2.7.15 though it just works out of the box here.
