### ISSUE TITLE
Platformio-ide-terminal Ubuntu 16.04 32 bits.

### ISSUE THREAD

**Issue by Aldot82** [platformio/platformio-atom-ide-terminal#476] opened 2018-03-15 16:17 UTC
Hello, i've installed atom in my machine, but there aren't any official version for linux 32 bits and i've installed atom from an external repository. I've tried to install platformio-ide-terminal and when y open the terminal doesn't show any prompt, only the cursor blinking.
Are there any solution?

Thanx!!

**Comment by cucu99** [comment] 2018-03-15 20:36
I got the same problem after upgrading my Atom to 1.25.0. Using Windows 10. 
Yesterday it ran smoothly.

**Comment by ivankravets** [comment] 2018-03-16 09:56
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/477

**Closed as completed by ivankravets** 2018-03-16 09:56 UTC
