### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by maqboolthoufeeq** [platformio/platformio-atom-ide-terminal#718] opened 2019-07-24 17:17 UTC
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\MaqboolThoufeeqT\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\MaqboolThoufeeqT\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\MaqboolThoufeeqT\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\MaqboolThoufeeqT\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\MaqboolThoufeeqT\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\MAQBOO~1\AppData\Local\Temp\apm-install-dir-119624-8408-1x6zn5j.7vq2\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\MAQBOO~1\AppData\Local\Temp\apm-install-dir-119624-8408-1x6zn5j.7vq2\package.json'
npm WARN apm-install-dir-119624-8408-1x6zn5j.7vq2 No description
npm WARN apm-install-dir-119624-8408-1x6zn5j.7vq2 No repository field.
npm WARN apm-install-dir-119624-8408-1x6zn5j.7vq2 No README data
npm WARN apm-install-dir-119624-8408-1x6zn5j.7vq2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MaqboolThoufeeqT\.atom\.apm\_logs\2019-07-24T17_15_44_507Z-debug.log

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment] 2019-07-24 17:19
@maqboolthoufeeq thanks for bring this issue to our attention.

This is a duplicate of #700 see https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround

**Closed as completed by the-j0k3r** 2019-07-24 17:19 UTC
Labels: duplicate

**Comment by maqboolthoufeeq** [comment] 2019-07-24 17:22
i can't find it, please provide the solution once again please

**Comment by the-j0k3r** [comment] 2019-07-24 17:25
see https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround

Its not hard this, click and it opens the correct comment.
