### ISSUE TITLE
Feature request: add a scroll-bar to terminal

### ISSUE THREAD

**Issue by fusion809** [platformio/platformio-atom-ide-terminal#41] opened 2016-06-09 10:37 UTC
Hi,

I think it'd help navigating the `platformio-ide-terminal` windows if a scroll-bar was added to it, similar to the scroll bar of `tree-view`. 

Thanks for your time,
Brenton

**Comment by MechCoder** [comment] 2016-07-15 04:28
Seconded, I would like scrolling support as well.

**Comment by ZCLMK** [comment] 2018-03-15 09:23
ctrl + arrow (up or down) allows you to scroll up or down !

**Comment by the-j0k3r** [comment] 2019-02-06 09:34
duplicate of #9

**Closed as completed by the-j0k3r** 2019-02-06 09:34 UTC
Labels: duplicate
