### ISSUE TITLE
Terminal doesn't open

### ISSUE THREAD

**Issue by rohan1599** [platformio/platformio-atom-ide-terminal#865] opened 2020-05-27 09:56 UTC
- [x] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by Vagrantin** [comment] 2020-06-17 08:49
- [x]  I have not reset Atom to defaults prior to submitting report.
### Description
Launching Platformio as usual either with keyboard shortcut or through the UI.
The bottom panel opens up correctly but then the shell is not accessible, and stuck for ever.
![image](https://user-images.githubusercontent.com/19902259/84876609-5be37a00-b0c2-11ea-9f73-04c10e149bce.png)

### Steps to reproduce
Install Platformio-ide-terminal
Launch Platformio-ide-terminal from the UI "Packages>Platformio-ide-terminal>Toggle"
### Expected behavior:
The terminal should be accessible, and I should be able to type in commands
### Actual behavior:
The bottom panel opens up correctly but then the shell is not accessible, and stuck for ever.
Cursor is blinking non-stop.
![image](https://user-images.githubusercontent.com/19902259/84876609-5be37a00-b0c2-11ea-9f73-04c10e149bce.png)

### Reproduces how often: 100%

### Versions

```
> atom --version
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

```
> apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.48.0
python 3.8.2
git 2.26.2.windows.1
visual studio 2015
```

OS name and version:  Windows 10 version 2004 (OS Build 19041.329)
Platformio-ide-terminal version:
![image](https://user-images.githubusercontent.com/19902259/84876156-e24b8c00-b0c1-11ea-9f13-fd23dec16956.png)

**Comment by Vagrantin** [comment] 2020-06-17 08:59
Looks like duplicate of #668

**Comment by the-j0k3r** [comment] 2020-07-15 12:42
Try https://github.com/bus-stop/terminus

**Closed as completed by the-j0k3r** 2020-07-15 12:42 UTC
