### ISSUE TITLE
Feature Request: allow docking the terminal on the right side of the screen

### ISSUE THREAD

**Issue by matthewgdv** [platformio/platformio-atom-ide-terminal#574] opened 2018-07-16 19:15 UTC
Hi,

I was just wondering if this could be done. This is an amazing package for atom, but it eats up too much useful screen space at the bottom on widescreen monitors (which are most monitors), whereas the right side of the screen is usually pretty empty anyway unless you have two panes open side-by-side. 

I'd like to be able to select where the terminal will dock to as an option, rather than begin forced to dock it to the bottom of the screen. Could this be done?

Thanks in advance.

**Comment by the-j0k3r** [comment] 2018-07-17 09:48
Its possible but if you want it you have to add it yourself, Sadly this project is no longer in active development its mainly basic maintenance only.

**Comment by archienorman11** [comment] 2018-11-23 17:10
This feature would be very helpful.

**Comment by the-j0k3r** [comment] 2019-02-07 11:53
pretty much is a duplicate of #198

**Closed as completed by the-j0k3r** 2019-02-07 11:53 UTC
Labels: duplicate, feature request
