### ISSUE TITLE
New UI based on tabs and docks

### ISSUE THREAD

**Issue by jaydenseric** [platformio/platformio-atom-ide-terminal#291] opened 2017-07-27 15:17 UTC
The current UI, consisting of a pop out panel with it's own tab system that spans the whole width of the window, is quite frustrating. Often I wish terminal tabs would just behave like ordinary workspace tabs, so they can be split and drag arranged wherever, with native close icons, etc.

Turns out someone has already started on a package that works just like that: [`atom-terminal-tab`](https://atom.io/packages/atom-terminal-tab). The behavior in the readme .gif is perfect. It supports Docks. When I tried it out, the UI and layout was great but there were a few rough edges about the functionality of the terminal itself that has be crawling back to `platformio-atom-ide-terminal`. New terminals don't open to the current project, and environment variables are not setting correctly for some reason.

Is there interest to adopt a new UI here?

**Comment by ivankravets** [comment] 2017-07-27 16:48
We are open for PR. Could you help us? This is a community-driven plugin. We maintain it.

**Comment by ivankravets** [comment] 2017-07-27 16:50
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/230

**Closed as completed by ivankravets** 2017-07-27 16:50 UTC
Labels: enhancement
