### ISSUE TITLE
Incompatible with Atom 1.39.0 beta 10 and newer

### ISSUE THREAD

**Issue by Zireael** [platformio/platformio-atom-ide-terminal#700] opened 2019-06-16 21:15 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description
I have upgraded to latest Atom version and getting this error message now:

![image](https://user-images.githubusercontent.com/3856578/59569583-7e901c80-9083-11e9-855c-ddc6ba9b3cdc.png)

### Steps to reproduce

1. Click View -> Terminal -> New Terminal Window

**Expected behavior:** 
Terminal works

**Actual behavior:** 

Terminal does not work.

I'm getting error message inside terminal window:

```
For more info check out the docs: https://nuclide.io/docs/features/terminal
Error starting process:
Error: The specified module could not be found.
\\?\C:\Users\xxx\.atom\packages\atom-ide-ui\node_modules\nuclide-prebuilt-libs\pty\build\pty-node-v64-win32-x64\pty.node
```

**Reproduces how often:**  100%

### Versions

```
> atom --version
Atom    : 1.39.0-beta1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
```
> apm --version
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.0-beta1
python 3.8.0b1
git 2.8.1.windows.1
visual studio 2015
```
OS name and version: Win 10 x64
Platformio-ide-terminal version: 2.9.1

**Comment by the-j0k3r** [comment] 2019-06-17 07:19
Hi @Zireael and thank you for reaching out with this issue report.

There are two things of note I see in your report.

1) Your version of Atom `1.39.0-beta10` with Node version `10.2.0` which requires a [node abi of 64]( https://github.com/lgeiger/node-abi/blob/79d73c3b676add0bd63899f021dabfa7e240be44/index.js#L57)

**Please test with the stable version of Atom. Because of (2)**

2) The error in your terminal is related to node-pty-prebuilt project as we use it as its this project dependency.

This is because [node-pty-prebuilt 0.7.6](https://github.com/daviwil/node-pty-prebuilt/releases/tag/v0.7.6) is latest release with Windows binaries up to node abi max version of **57** and only supports [Node up to version 8.0.0](https://github.com/lgeiger/node-abi/blob/79d73c3b676add0bd63899f021dabfa7e240be44/index.js#L55) and [electron up to 2.0.0](https://github.com/lgeiger/node-abi/blob/79d73c3b676add0bd63899f021dabfa7e240be44/index.js#L68)

As such marked this as external because there are no Windows **node-pty-prebuilt with Windows binaries** that support higher Node/Electron versions.

**Please make a comment in related issue** that would solve this report @ https://github.com/daviwil/node-pty-prebuilt/issues/14

When node-pty-prebuilt 0.8.1 or newer comes out with Windows (or insertyourOSherebinaries), then you need to uninstall/reinstall platformio-ide-terminal in the beta versions of Atom. Until then you have to stick with stable versions of Atom or contribute a fix the Windows builds in node-pty-prebuilt repo.

Here in this project, we are at the projects dependencies mercy and I cant submit that fix, even if I did @daviwil is an extremely busy person and not frequently active in node-pty-prebuilt project either probably due to other professional responsibilities.

Thanks in advance for your understanding.

**Comment by the-j0k3r** [comment] 2019-06-19 09:04
@Zireael Any feedback after my reply?

**Comment by jvanderzande** [comment] 2019-06-30 17:17
> Please test with the stable version of Atom. Because of (2)

I have added a post in the linked project having the same issue, but reverting to the latest stable version hasn't worked for me yet and is giving me the same error. Is there anything I need to do before running the latest production installer to reset everything and make that work?

Cheer, Jos

**Comment by the-j0k3r** [comment] 2019-07-01 07:03
>Is there anything I need to do before running the latest production installer to reset everything and make that work

@jvanderzande

Understand that simple stating your issue is not enough to even guess what may be the issue.
If you are looking for help, you must [fill in our issue template fully and including any extra details at the bottom](https://github.com/platformio/platformio-atom-ide-terminal/blob/master/.github/ISSUE_TEMPLATE.md) like screenshots or error logs or anything else helpful like a list of 3rd party antivirus/softwares you have installed. (McAffee is known to interfere with Atom for instance).

This way we can have actionable information and try to see if there is anything we can do to, help us, help you better.

Thanks for understanding.

**Comment by jvanderzande** [comment] 2019-07-01 10:38
I didn't want to create yet another issue, as I have the same issue as reported here, just reverting back to the old production still doesn't download the platformio-ide-terminal older version and it still seems to point the Beta I had installed when the problem started. In the meantime I found some remaining old files in directory "C:\Users\xxxxxx\AppData\Roaming\Atom" which I renamed after which the next start of Atom everything worked fine and that directory was regenerated. 
Hope this helps other having this issue and thanks for your support.

**Comment by the-j0k3r** [comment] 2019-07-01 13:36
>I didn't want to create yet another issue

No need, just replying to the comment in this issue with the template filed in, is infinitely more helpful to someone trying to help you, than just a _me too report_. 

>just reverting back to the old production still doesn't download the platformio-ide-terminal older version

I think you meant to write Atom, ;)

>and it still seems to point the Beta I had installed when the problem started. In the meantime I found some remaining old files in directory "C:\Users\xxxxxx\AppData\Roaming\Atom"

Atom documentation is what you would have wanted, [particularly the part about resetting Atom to defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) which is what you ended up doing in a roundabout way.

>which I renamed after which the next start of Atom everything worked fine and that directory was regenerated.

Yes, its recreated (it has to), but with the production version of Atom files instead of your beta file contents which like you aptly found out, fouling up the intended downgrade.

> Hope this helps other having this issue and thanks for your support.

Hope is a good choice of words, so do I. And youre welcome.

On a second note, node-pty-prebuilt developer/maintainer @daviwil GtHub page indicates a change of employer, if this will affect that project IDK, This project relies on that project, so you/others may want to find out how to compile the required binaries for Windows/<insertyourOShere> when Atom production node/electron versions reach unsupported ABI we know will break as reported here. That or find another Terminal project for Atom or move to VScode.

**Comment by birnstiel** [comment] 2019-07-24 12:19
1.39.0 is out and platformio-ide-terminal still won't install (at least on macOS). Are there any fixes in sight?

**Comment by the-j0k3r** [comment] 2019-07-24 12:25
@birnstiel nope, the issue is node-pty-prebuilt has no binaries for the new node/electron for Windows and macOS.

You can try (read from that comment and below) this https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514454289

Failing that we are royally stuffed.

**Comment by clair513** [comment] 2019-07-24 14:45
@the-j0k3r Adding a log file for this issue, only if it helps. Though as you stated, I understand there isn't an immediate fix. BTW [#707 (Comment)](https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895) helps!

[2019-07-24T14_40_56_779Z-debug.log](https://github.com/platformio/platformio-atom-ide-terminal/files/3427355/2019-07-24T14_40_56_779Z-debug.log)

**Comment by the-j0k3r** [comment] 2019-07-24 14:48
@clair513 logs wont help, we know what the issue is in this case. But Im very happy to hear that that workaround works.

Take care.

**Comment by chd1998** [comment] 2019-07-25 04:43
Same error occured to me now.
When I upgrade to Atom 1.39.0, platformio-ide-terminal failed to start...

**Comment by the-j0k3r** [comment] 2019-07-25 05:54
@chd1998 

See https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround, @clair513 had already posted this above.

**Comment by ivankravets** [comment] 2019-07-31 08:26
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/707

**Closed as completed by ivankravets** 2019-07-31 08:26 UTC
Labels: wontfix, external

**Comment by ivankravets** [comment] 2019-08-01 21:10
Please upgrade to https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.9.2

**Comment by the-j0k3r** [comment] 2019-08-02 05:27
sadly already broken reports

https://github.com/platformio/platformio-atom-ide-terminal/issues/755
