### ISSUE TITLE
Need search capability

### ISSUE THREAD

**Issue by ssilverman** [platformio/platformio-atom-ide-terminal#173] opened 2017-02-21 12:20 UTC
It's extremely difficult to track down errors when, for example, -Wconversion, is enabled on the compiler and there are thousands of lines of warnings. Terminal would benefit greatly from search.

**Comment by the-j0k3r** [comment] 2019-02-07 15:30
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/121

**Closed as completed by the-j0k3r** 2019-02-07 15:30 UTC
Labels: duplicate
