### ISSUE TITLE
[windows] the "cls" command can't clear previous commands

### ISSUE THREAD

**Issue by speedornothing** [platformio/platformio-atom-ide-terminal#111] opened 2016-11-27 10:19 UTC
previous commands still exist after executing the "cls" command. You can see them when scrolling up

**Comment by the-j0k3r** [comment] 2019-02-07 09:18
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/65

**Closed as completed by the-j0k3r** 2019-02-07 09:18 UTC
Labels: duplicate
