### ISSUE TITLE
I have been having difficulty installing platformio-ide-terminal. I click install from Atom's settings view and it would appear installing but stops all of a sudden

### ISSUE THREAD

**Issue by Jybes** [platformio/platformio-atom-ide-terminal#698] opened 2019-06-11 09:45 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment] 2019-06-11 09:46
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/637

Not filling in the issue template is not helpful though. [Please read this](https://github.com/platformio/platformio-atom-ide-terminal/issues/637#issuecomment-495907966).

**Closed as completed by the-j0k3r** 2019-06-11 09:46 UTC
Labels: duplicate, wontfix, external
