### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by ayushgupta321** [platformio/platformio-atom-ide-terminal#661] opened 2019-02-25 07:43 UTC
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

The terminal does not seem to work. A blinking cursor appears ,but I cannot write anything.

### Steps to reproduce

1. Install platform-atom-ide-terminal
2. Click on + icon at the bottom

**Expected behavior:** 
I expected the Windows PowerShell to open. I even changed the override to cmd.exe(with the correct path) ,yet nothing seems to change

**Actual behavior:** 
Blinking Cursor appears ,cannot type anything.

**Reproduces how often:** 
100%

### Versions

```
> atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
> apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.6.6
git
visual studio
```
OS name and version:
Platformio-ide-terminal version:
2.9.1

### Additional Information

![ss](https://user-images.githubusercontent.com/35401492/53321557-d51ff200-38fe-11e9-9869-5246e800b366.png)

**Comment by Kreyren** [comment] 2019-02-26 20:59
I have same issue on ubuntu 18.10
```
kreyren@kreyren:~$ atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by zer0-u** [comment] 2019-03-06 13:34
I have same issue on windows version 1803 (OS Build 17134.590) (Japanese)

```
atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by the-j0k3r** [comment] 2019-03-06 13:42
Thank you for reaching out with this bug report.

All me too reports please fill the issue template

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Thank you for your understanding.

Also this is a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/668 so please add your information to that report instead please.

@ayushgupta321 Im transplanting your report to  #668

**Closed as completed** 2019-03-06 13:43 UTC
Labels: duplicate, more information required
