### ISSUE TITLE
PSReadline issue

### ISSUE THREAD

**Issue by collins73** [platformio/platformio-atom-ide-terminal#423] opened 2017-12-01 23:09 UTC
Cannot load PSReadline module. Console is running without PSReadline.

Any ideas or fixes for this problem?

**Comment by collins73** [comment] 2017-12-01 23:15
I still cannot resolve this issue.. I will use my command prompt that came with computer

**Comment by the-j0k3r** [comment] 2019-02-06 16:56
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/64 which also has a solution.

**Closed as completed by the-j0k3r** 2019-02-06 16:56 UTC
Labels: duplicate
