### ISSUE TITLE
terminal open but cursor keeps blinking and i cannot type

### ISSUE THREAD

**Issue by ianindratama** [platformio/platformio-atom-ide-terminal#765] opened 2019-08-10 08:32 UTC
I already look to most of the solution about this,i have uninstalled the package and reboot my pc then install the package again but it just didnt work.
Note : i already look up for the solution in https://github.com/platformio/platformio-atom-ide-terminal/issues/760 but still cannot solve the problem

![image](https://user-images.githubusercontent.com/53966296/62819753-47724f00-bb8c-11e9-9926-58bedfc8055e.png)
im using windows 10,my atom version is 1.39.1 x64 and the platformio-ide-terminal version is 2.9.3

**Comment by idebtor** [comment] 2019-08-10 16:25
It happens when I started using atom 1.39.1 x64 and platformio-ide-terminal@2.9.3 in windows 10.  The solution in #760 did not work.  I even tried a few similar terminals, the same symptom is observed.  The problem could be in Atom, not in platform-ide-terminal@2.9.3.  However, BETA and Nightly versions of Atom did not help either. 

By the way, finally, I made it work. 
1. uninstalled platform-ide-terminal and then atom.  
2. installed atom 1.39.1 x64 
3. followed the solution #760 suggested, but used  "apm i" instead of "npm i".

(a debtor)<><

**Comment by achmadkhodzim** [comment] 2019-08-10 17:55
same problem here

**Comment by a-boyajian** [comment] 2019-08-11 04:44
same here

**Comment by the-j0k3r** [comment] 2019-08-11 06:18
This is a duplicate of #760 

Workarounds are up in #760 and a fix in https://github.com/platformio/platformio-atom-ide-terminal/pull/764

Please do not ignore the issue template fields in future, this sort of disregard isnt helpful in any case, in this instance the issue is well know, and, many duplicates to #700 have been filed including yours.

**Closed as completed by the-j0k3r** 2019-08-11 06:18 UTC
Labels: duplicate
