### ISSUE TITLE
blank terminal

### ISSUE THREAD

**Issue by dimaskpz** [platformio/platformio-atom-ide-terminal#557] opened 2018-06-25 03:38 UTC

**Comment by Yannny** [comment] 2018-06-25 06:13
There is a new update v2.8.3 that should fix the bug.

**Comment by the-j0k3r** [comment] 2018-06-26 01:07
Thank you for your detailed and exhaustive bug report.

This is a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/555

@ivankravets please close :)

**Closed as completed** 2018-06-26 06:59 UTC

**Comment by dimaskpz** [comment] 2018-06-26 09:13
thankyou
