### ISSUE TITLE
uncaught channel closed

### ISSUE THREAD

**Issue by blackviking110** [platformio/platformio-atom-ide-terminal#592] opened 2018-08-22 07:54 UTC
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (C:\Users\SHRIYESH SUKUMARAN\AppData\Local\atom\app-1.29.0\resources\app\src\task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/SHRIYESH SUKUMARAN/.atom/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at Terminal.<anonymous> (file:///C:/Users/SHRIYESH SUKUMARAN/.atom/packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (C:\Users\SHRIYESH SUKUMARAN\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\SHRIYESH SUKUMARAN\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3493:8)
    at C:\Users\SHRIYESH SUKUMARAN\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3253:12

**Comment by the-j0k3r** [comment] 2018-08-22 13:27
This is a duplicate of #556

@ivankravets please close. (I think we need a user issue template)

@blackviking110 reply in #556 try  whats posted in https://github.com/platformio/platformio-atom-ide-terminal/issues/556#issuecomment-412977328

**Closed as completed** 2018-08-22 21:35 UTC
