### ISSUE TITLE
terminal and serial monitor have stopped working after today's platformio update

### ISSUE THREAD

**Issue by Hristo05** [platformio/platformio-atom-ide-terminal#485] opened 2018-03-16 17:21 UTC
terminal and serial monitor have stopped working after today's platformio update. Can't see any error message nor advice anywhere.
Tried to uninstall and reinstall, no luck.
Still works perfectly with Arduino IDE.

**Comment by ivankravets** [comment] 2018-03-16 17:39
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/477#issuecomment-373765626

**Closed as completed by ivankravets** 2018-03-16 17:39 UTC
