### ISSUE TITLE
NOT TYPING

### ISSUE THREAD

**Issue by michyscholar123** [platformio/platformio-atom-ide-terminal#528] opened 2018-05-08 20:48 UTC

**Comment by michyscholar123** [comment] 2018-05-08 20:49
INSTALLED TERMINAL ANT IS NOT TYPING? ANY IDEAS HOE TO FIX IT??

**Comment by the-j0k3r** [comment] 2018-07-05 14:14
duplicate of #500 

@ivankravets please add a duplicate label, close at your discretion.

**Closed as completed** 2018-07-05 20:39 UTC
Labels: duplicate
