### ISSUE TITLE
can not install platformio-ide-terminal 

### ISSUE THREAD

**Issue by udayverma8898** [platformio/platformio-atom-ide-terminal#709] opened 2019-07-24 10:43 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Whenever I try to install platformio-ide-terminal in atom i get the following error-

```log
> node-pty-prebuilt@0.7.6 install C:\Users\Lenovo\AppData\Local\Temp\apm-install-dir-119624-9724-1fhcgu3.kun2\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\Lenovo\AppData\Local\Temp\apm-install-dir-119624-9724-1fhcgu3.kun2\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Lenovo\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\Lenovo\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Lenovo\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Lenovo\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Lenovo\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\Lenovo\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Lenovo\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\Lenovo\AppData\Local\Temp\apm-install-dir-119624-9724-1fhcgu3.kun2\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Lenovo\AppData\Local\Temp\apm-install-dir-119624-9724-1fhcgu3.kun2\package.json'
npm WARN apm-install-dir-119624-9724-1fhcgu3.kun2 No description
npm WARN apm-install-dir-119624-9724-1fhcgu3.kun2 No repository field.
npm WARN apm-install-dir-119624-9724-1fhcgu3.kun2 No README data
npm WARN apm-install-dir-119624-9724-1fhcgu3.kun2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\.atom\.apm\_logs\2019-07-24T10_20_23_158Z-debug.log
```

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

1.39.0
```
```
> apm --version
2.2.4
```
OS name and version: Windows 10 version 1903
Platformio-ide-terminal version: trying to install version 2.9.1

**Comment by the-j0k3r** [comment] 2019-07-24 12:00
@udayverma8898 Thanks for bringing this issue to our attention.

This is a duplicate of #700 and there is nothing we can do about it at this time.

**Closed as completed by the-j0k3r** 2019-07-24 12:00 UTC
Labels: duplicate
