### ISSUE TITLE
platformio-atom-ide@2.9.1.  installation failed

### ISSUE THREAD

**Issue by y-khan** [platformio/platformio-atom-ide-terminal#673] opened 2019-03-10 21:34 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [X] I have not reset Atom to defaults prior to submitting report.
### Description

I am trying to install 2.9.1. but it fails to install. Getting the following error report. 

Installing “platformio-ide-terminal@2.9.1” failed.Hide output…

> node-pty-prebuilt@0.7.6 install C:\cygwin64\tmp\apm-install-dir-119210-16876-1vina5q.76iv\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js

npm WARN lifecycle npm is using C:\Users\myk10\AppData\Local\atom\app-1.34.0\resources\app\apm\bin\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
'node' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\cygwin64\tmp\apm-install-dir-119210-16876-1vina5q.76iv\package.json'
npm WARN apm-install-dir-119210-16876-1vina5q.76iv No description
npm WARN apm-install-dir-119210-16876-1vina5q.76iv No repository field.
npm WARN apm-install-dir-119210-16876-1vina5q.76iv No README data
npm WARN apm-install-dir-119210-16876-1vina5q.76iv No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment] 2019-03-11 06:20
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/637 despite different errors its all same.

The relevant part is

```
npm WARN lifecycle npm is using C:\Users\myk10\AppData\Local\atom\app-1.34.0\resources\app\apm\bin\node.exe but there is no node binary in the current PATH. Use the --scripts-prepend-node-path option to include the path for the node binary npm was executed with.
'node' is not recognized as an internal or external command,
operable program or batch file.
'node' is not recognized as an internal or external command,
operable program or batch file.
```

Try do what it says. **Use the --scripts-prepend-node-path option to include the path for the node binary npm was executed with.**

This is apm/node-pty-prebuilt installer related, we cant control 3rd party installers and their occasional issues they throw. Best kkep trying at differnt times or with a vpn/proxy, best complain to them ;)

**Closed as completed by the-j0k3r** 2019-03-11 06:20 UTC
Labels: duplicate, wontfix, external

**Comment by the-j0k3r** [comment] 2019-05-25 10:55
# Reminder: 

Any installation issues [are to and should be reported to apm issue tracker](https://github.com/atom/apm/issues/new) **platformio-ide-terminal** cannot control **apm** which **is responsible for installs of all atom plugins and their dependencies** anyway, so **thanks in advance for your understanding in these matters**.
