### ISSUE TITLE
Blinking Cursor, no prompt shown

### ISSUE THREAD

**Issue by ychuckt8** [platformio/platformio-atom-ide-terminal#676] opened 2019-03-21 02:13 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
`
> apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 3.6.5
git 2.20.1.windows.1
visual studio 2015
```
OS name and version: WIN10
Platformio-ide-terminal version: 2.9.1
### Additional Information
<!-- Add any additional information like screenshots, gif captures,
configuration, data or other Atom package lists, that might be necessary to reproduce the issue. -->

**Comment by the-j0k3r** [comment] 2019-03-21 05:30
Thank you for reaching out with this report.

2 things to point out.

1) The issue template must be filled in 100%.
2) This is a duplicate of #668.

If you wish to fill in the template fully and make a post in #668 with the whole information, this will be what should happen, we wont accept bug reports without a fully filled in issue template.

Please refer to #668 for posting **"me too"**. reports and subsequent comments.

Thank you for understanding. =)

**Closed as completed by the-j0k3r** 2019-03-21 05:30 UTC
Labels: duplicate
