### ISSUE TITLE
copy/paste turns space into non-breaking-space

### ISSUE THREAD

**Issue by colin-kiegel** [platformio/platformio-atom-ide-terminal#211] opened 2017-04-09 12:22 UTC
Sometimes I want to copy a command from the terminal output and run it, but that doesn't work.

# Steps to reproduce

Linux / Atom 1.14.4 x64 / platformio-ide-terminal 2.5.0

```
$ echo cd .   # <-- type manually
cd .          # <-- select and copy
$ cd .        # <-- paste and return
cd .: command not found
```

The following hexdumps confirms that copy pasting turns spaces into non-breaking-spaces:

```
$ echo cd . | xxd # <-- type manually
00000000: 6364 202e 0a                             cd ..
$ echo cd . | xxd # <-- type manually except for `cd .` which is copy-pasted
00000000: 6364 c2a0 2e0a                           cd....
```

<details>
<summary>UTF8 chars</summary>
<pre>
<a href="http://www.utf8-chartable.de/">http://www.utf8-chartable.de/</a>
   63 | c
   64 | d
   20 | SPACE
   2e | .
   0a | LINE FEED
c2 a0 | NO-BREAK SPACE
</pre>
</details>

**Comment by colin-kiegel** [comment] 2017-04-09 12:52
The same problem happens also if I copy out of platformio-ide-terminal into a native terminal of my system.

This might be related to #76. It looks like `<br />` and `&nbsp;` are used to control the formatting. I imagine that non-breaking spaces are supposed to stop browsers from stripping spaces.

I believe the `&nbsp;` problem can be solved when using `white-space: pre` or `pre-wrap` for formatting. However line wraps would still either need `<br />` or behave a bit differently than usual terminals. This is because html tries to preserve words, if it can wrap after a whitespace instead. Even with `word-wrap: break-word` a word will only be broken if it exceeds the width of one line - in all other cases html will break on whitespaces instead. Although both problems are related, the solution might be different. It looks like the newline problem might be harder to solve.

**Comment by laubblatt** [comment] 2017-04-18 12:27
I can confirm this issue, which is very annoying when working with R or bash commands using the platformio-ide-terminal. The problem is even worse when soft-wrap is on.

**Comment by sagarey** [comment] 2017-09-20 08:28
+1, It's so annoying.

**Comment by miccio-dk** [comment] 2017-09-20 10:27
+1, it's quite a pain :/

**Comment by sagarey** [comment] 2017-09-25 09:57
It seems to be cause by selectToCopy method, it works well for me now #373

**Comment by ivankravets** [comment] 2017-09-25 16:21
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/issues/211#issuecomment-330811710

**Closed as completed by ivankravets** 2017-09-25 16:21 UTC
Labels: PR welcome
